services:
  tgd-maintenance-soft-db:
    image: mysql:9
    container_name: tgd-maintenance-soft-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tgd-maintenance-soft-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
